### ISSUE TITLE
영역 선택 후 Ctrl+C가 동작하지 않습니다.

### ISSUE THREAD

**Issue by yanoo824** [pat-al/Online-Hangeul-IME#7]
안녕하세요.

영역 선택 후 Ctrl+C가 동작하지 않습니다. 영역 선택은 마우스 드래그나 shift 키를 누르고 화살표키로 하였습니다.

7/24 즈음에 수정하신 부분에 문제가 있는 것으로 생각됩니다.

Ctrl+A 누르고 Ctrl 키를 떼지않고 C를 누르면 동작은 합니다.

수정 부탁드려도 될까요?

**Comment by pat-al** [comment]
불편을 끼쳐서 죄송합니다.
Ctrl 글쇠가 들어가는 기능 글쇠를 눌렀을 때 한글 조합이 안 끊어지는 걸 막으려다가
Ctrl+C, Ctrl+X 등이 작동하지 않는 문제를 일으키고 말았습니다.
현재 Ctrl이 들어가는 기능 글쇠 동작이 잘 되게 고친 코드를 올려 놓았습니다.

**Comment by yanoo824** [comment]
감사합니다! Ctrl+Z도 안되는 데 이것도 고쳐주실 수 있을까요?
죄송하실 거는 없습니다 :)

**Comment by pat-al** [comment]
관련 있는 글들과 예제가 될 만 한 곳을 살펴 봤는데,
OHI처럼 정규 IME를 통하지 않고 글상자(textarea)에 관여하면 Ctrl+Z 동작이 안 되는 것 같습니다.
글 내용을 저장해서 Ctrl+Z 동작을 따로 구현하는 스크립트를 넣어야 가능할 것 같은데,
그렇게 하면 거의 웹 에디터 수준으로 판을 키우게 되는 게 부담스럽습니다.
당장은 어려울 것 같고, 할 수 있는지 차차 궁리는 해 보겠습니다.

**Comment by yanoo824** [comment]
답변 감사드립니다.

OHI orginal version(http://ohi.pat.im/org/)에서는 crrl+z 동작하는데요. 참조해주시면
감사하겠습니다.

**Comment by pat-al** [comment]
제가 윈도우 10에서 엣지, 크롬, 파이어폭스로 확인했을 때에는
OHI가 제대로 작동하는 때에는 http://ohi.pat.im/org 에서도 Ctrl+Z와 Ctrl+Y가 작동하지 않았습니다.
요즘판 파이어폭스는 OHI 원판이 제대로 작동하지 않아서 잘 되더라도 뜻은 없습니다.
IE는 OHI 원판과 현재판 모두 Ctrl+Z가 작동은 하는데, 작동하는 내용이 정확하지 않고 불완전합니다.

우분투도 쓰지만 파이어폭스만 쓰고 있어서 비교를 제대로 못했습니다.
혹시 OHI 원판이 잘 작동한다면 어떤 운영체제와 웹 누비개(웹 브라우저)에서 잘 작동하는지 알려 주시면 좋겠습니다.
운영체제 같은 환경에 따라 다를지도 모르겠습니다.

**Comment by yanoo824** [comment]
안녕하세요. 말씀주신대로 OHI 원판이 버그가 있습니다. 단어입력 후 스페이스 바를 누르면 두칸 띄어쓰기가 되는 버그가 있고요.
Windows 10, 크롬에서 OHI 원판 위 버그가 있으나 ctrl+z, y동작합니다. 두 컴퓨터에서 언어를 영어로 해서 확인을
하였습니다.

컴퓨터 환경은
Windows 10 Home 1903
Chrome Version 75.0.3770.142 (Official Build) (64-bit)
입니다.

**Comment by pat-al** [comment]
제가 확인해 보면,
크롬으로 OHI 원판에서 OHI를 통한 한글 입력 상태를 만들어 놓으면
Ctrl+Z와 Ctrl+Y 동작이 안 되거나 엉망이 됩니다.
OHI가 작동하지 않는 때는 Ctrl+Z와 Ctrl+Y가 잘 작동됩니다.
윈도우에서 쓰는 IME들의 한/영 상태를 바꿔서 하나하나 비교해 보아도 결과는 마찬가지입니다.
왜 서로 다른 결과가 나오는지는 도통 모르겠습니다.

제가 쓴 환경은 다음과 같습니다.

Windows 10 Pro (1903 10.0.18362.239)
버전 76.0.3809.87(공식 빌드) (64비트)
IME : 날개셋, 한국어 MS 입력기, 한국어 MS 옛한글

현재 OHI는 Ctrl이 들어가는 기능 글쇠가 눌린 때에 한글 조합을 그만둘 뿐이고,
예전부터 OHI가 Ctrl+Z나 Ctrl+Y를 일부러 막거나 끼어들지는 않고 있습니다.
OHI가 Ctrl+C나 Ctrl+X에 직접 관여하지 않아도 알아서 되는 것처럼,
Ctrl+Z도 OHI와는 무관하게 웹 누비개나 정규 IME에 얽혀서 작동하고 있습니다.
OHI가 자판 배열을 반영하여 문자를 넣을 때 정규 IME를 막아서고 지저분하게 끼어드는 것 때문에
Ctrl+Z 기능에 걸림돌이 되는 것 같다고 짐작만 하고 있습니다.

또 OHI는 특정한 textarea나 input 객체만 겨냥해서 작동하지 않습니다.
웹 페이지 안에서 커서가 놓인 객체에서 거의 다 작동합니다.
이 점 때문에 Ctrl+Z 기능을 구현하는 스크립트를 따로 만들어 넣는다면,
객체마다 따로 글 내용을 기억시켜야 할지가 것이 좀 고민스럽습니다.

OHI 원판이 웹 환경이 바뀜에 따라 고르게 작동하지 않는 기능이 생긴 것처럼,
어렵사리 Ctrl+Z 기능을 구현하더라도 유지/관리가 어려워질 가능성이 있습니다.
그래서 아직 자체 기능 구현에 대하여는 희망찬 답변을 드릴 수 없는 점을 양해해 주셨으면 합니다.
일단은 OHI에 따로 기능을 넣지 않고 정규 IME나 웹 누비개에 기대는 쪽이 좋겠다고 생각하고 있습니다.

**Comment by yanoo824** [comment]
ctrl+z, ctrl+y가 정상동작하지는 않는데요.
글을 쓰고 백스페이스를 여러번 누르고 ctrl+z 누르는 것은 동작합니다.

답변을 읽어보니 ctrl+z 기능은 적용이 어려워 보이네요.
답변 감사드립니다!

**Comment by yanoo824** [comment]
감사합니다!!
